Make kvm-admin fail when passed an invalid option.
Better to do this instead of spinning forever.

diff --git a/tools/kvm-admin b/tools/kvm-admin
--- a/tools/kvm-admin
+++ b/tools/kvm-admin
@@ -46,6 +46,13 @@ while [[ $1 ]]; do
             fi
             ephemeral_admin=true
             shift 2;;
+        *)
+            echo "Invalid options: ${*}"
+            echo "Please try one of:"
+            echo "   --save-image <file> to save the admin disk image after kvm-admin is killed,"
+            echo "   --demo <file> to run a previosly-saved image discarding changes,"
+            echo "   --use-image <file> to run a previously-saved image keeping changes"
+            exit 1;;
     esac
 done
 
